#!/usr/bin/env bash
source demo.env

# Tell the user what we're doing:
printf "Creating Azure Virtual Network: '${NAME_NET}' \n"
printf "Running Command: \n"
printf "az aks create \\
--resource-group ${RESOURCE_GROUP_NAME} \\
--name ${CLUSTER_NAME} \\
--node-count ${COUNT_NODE} \\
--generate-ssh-keys  \\
--network-plugin azure  \\
--service-cidr ${CIDR_SVC}  \\
--dns-service-ip ${ADDR_DNS}  \\
--docker-bridge-address ${CIDR_DKR}  \\
--vnet-subnet-id ${SUBNET_ID} \\
--service-principal ${SP_ID} \\
--client-secret ${SP_PASSWORD} \\
--enable-addons monitoring \n"

# Run command:
az aks create \
--resource-group ${RESOURCE_GROUP_NAME} \
--name ${CLUSTER_NAME} \
--node-count ${COUNT_NODE} \
--generate-ssh-keys  \
--network-plugin azure  \
--service-cidr ${CIDR_SVC}  \
--dns-service-ip ${ADDR_DNS}  \
--docker-bridge-address ${CIDR_DKR}  \
--vnet-subnet-id ${SUBNET_ID} \
--service-principal ${SP_ID} \
--client-secret ${SP_PASSWORD} \
--enable-addons monitoring
